### ISSUE TITLE
Installation Error

### ISSUE THREAD

**Issue by aztrix** [dmidlo/histdata.com-tools#26]
Hi David

i received the following error when installing pyMS:

![image](https://user-images.githubusercontent.com/454294/172056930-60a9059e-6764-4557-b2e6-7e84c99b7626.png)

(base) PS C:\WINDOWS\system32> pip install pyms
Collecting pyms
  Using cached pyms-0.1.0.tar.gz (6.7 kB)
    ERROR: Command errored out with exit status 1:
     command: 'C:\ProgramData\Anaconda\python.exe' -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'D:\\Users\\XXXXX\\AppData\\Local\\Temp\\pip-install-rnjksrk3\\pyms_b5fbdf76c1f34e369c49738a4f6c2113\\setup.py'"'"'; __file__='"'"'D:\\Users\\XXXXX\\AppData\\Local\\Temp\\pip-install-rnjksrk3\\pyms_b5fbdf76c1f34e369c49738a4f6c2113\\setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base 'D:\Users\XXXXX\AppData\Local\Temp\pip-pip-egg-info-9mff968f'
         cwd: D:\Users\XXXXX\AppData\Local\Temp\pip-install-rnjksrk3\pyms_b5fbdf76c1f34e369c49738a4f6c2113\
    Complete output (7 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "D:\Users\XXXXX\AppData\Local\Temp\pip-install-rnjksrk3\pyms_b5fbdf76c1f34e369c49738a4f6c2113\setup.py", line 49, in <module>
        install_requires=get_requirements('requirements.txt'),
      File "D:\Users\XXXXX\AppData\Local\Temp\pip-install-rnjksrk3\pyms_b5fbdf76c1f34e369c49738a4f6c2113\setup.py", line 30, in get_requirements
        f = open(filename).read()
    FileNotFoundError: [Errno 2] No such file or directory: 'requirements.txt'
    ----------------------------------------
WARNING: Discarding https://files.pythonhosted.org/packages/56/77/8f530008fb03dded3d580d2bd2fe2d79db6f46a60ee9da4a9737d75218de/pyms-0.1.0.tar.gz#sha256=58b8cbf3e96616b53a080ce76e69ed05b4f220bc4a8be8cfdf93e264c6fd0382 (from https://pypi.org/simple/pyms/). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
ERROR: Could not find a version that satisfies the requirement pyms (from versions: 0.1.0)
ERROR: No matching distribution found for pyms

What am I missing other than requirements.txt?

Regards
Aztrix

**Comment by dmidlo** [comment]
I'm not sure that this is related to histdata.com-tools. PyMS is not a direct dependency of this project

That being said, it looks like your `pip install pyms` should be `pip install py-ms[all]`

Check out the [pyms repo](https://github.com/python-microservices/pyms) for more info.

**Comment by aztrix** [comment]
Thanks for getting back to me David, much appreciated

 

I’m a newbie in the Python world but trying to get my head around it. Currently running Python 3.8 using Anaconda and have now managed to install both datatable and histdatacom but when I run histdatacom -h I get the following error:

(base) PS C:\WINDOWS\system32> histdatacom -h

Traceback (most recent call last):

  File "C:\ProgramData\Anaconda\lib\runpy.py", line 194, in _run_module_as_main

    return _run_code(code, main_globals, None,

  File "C:\ProgramData\Anaconda\lib\runpy.py", line 87, in _run_code

    exec(code, run_globals)

  File "C:\ProgramData\Anaconda\Scripts\histdatacom.exe\__main__.py", line 4, in <module>

  File "C:\ProgramData\Anaconda\lib\site-packages\histdatacom\__init__.py", line 9, in <module>

    from . import histdata_com

  File "C:\ProgramData\Anaconda\lib\site-packages\histdatacom\histdata_com.py", line 2, in <module>

    from histdatacom.cli import ArgParser

  File "C:\ProgramData\Anaconda\lib\site-packages\histdatacom\cli.py", line 71, in <module>

    from histdatacom.fx_enums import Pairs

  File "C:\ProgramData\Anaconda\lib\site-packages\histdatacom\fx_enums.py", line 177

    match csv_format:

          ^

Do you know what’s causing this or do you have a version of histdata.com-tools that supports Python 3.8?

 

Cheers

Bruce

**Comment by aztrix** [comment]
BTW I did create a Python 3.10 environment with conda, histdatacom installs fine but datatable is another story …

 

 

From: ***@***.*** ***@***.***> 
Sent: 19 June 2022 4:14 AM
To: 'dmidlo/histdata.com-tools' ***@***.***>; 'dmidlo/histdata.com-tools' ***@***.***>
Cc: 'Author' ***@***.***>
Subject: RE: [dmidlo/histdata.com-tools] Installation Error (Issue #26)

 

Thanks for getting back to me David, much appreciated

 

I’m a newbie in the Python world but trying to get my head around it. Currently running Python 3.8 using Anaconda and have now managed to install both datatable and histdatacom but when I run histdatacom -h I get the following error:

(base) PS C:\WINDOWS\system32> histdatacom -h

Traceback (most recent call last):

  File "C:\ProgramData\Anaconda\lib\runpy.py", line 194, in _run_module_as_main

    return _run_code(code, main_globals, None,

  File "C:\ProgramData\Anaconda\lib\runpy.py", line 87, in _run_code

    exec(code, run_globals)

  File "C:\ProgramData\Anaconda\Scripts\histdatacom.exe\__main__.py", line 4, in <module>

  File "C:\ProgramData\Anaconda\lib\site-packages\histdatacom\__init__.py", line 9, in <module>

    from . import histdata_com

  File "C:\ProgramData\Anaconda\lib\site-packages\histdatacom\histdata_com.py", line 2, in <module>

    from histdatacom.cli import ArgParser

  File "C:\ProgramData\Anaconda\lib\site-packages\histdatacom\cli.py", line 71, in <module>

    from histdatacom.fx_enums import Pairs

  File "C:\ProgramData\Anaconda\lib\site-packages\histdatacom\fx_enums.py", line 177

    match csv_format:

          ^

Do you know what’s causing this or do you have a version of histdata.com-tools that supports Python 3.8?

 

Cheers

Bruce

**Comment by dmidlo** [comment]
@aztrix I've added setup steps for [Anaconda Windows Using the Anaconda Prompt](https://github.com/dmidlo/histdata.com-tools#anaconda-windows-using-the-anaconda-prompt).  Let me know that this does work for you in your environment.  Thanks for pointing out these issues!

**Comment by dmidlo** [comment]
Closing this as resolved

**Comment by aztrix** [comment]
@dmidlo you're a bloody legend, many thanks for all the setup and instructions, worked like a charm except for the && which I just separated

Coffee coming up ☕
